[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', "node_modules"]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = 'long'
func_attrs_with_params_multiline = true
quote_style = 'double'
number_underscore = 'preserve'
multiline_func_header = 'params_first'

[fuzz]
runs = 10

[rpc_endpoints]
bsc = "https://bsc-dataseed1.binance.org/"
bsc-test = "${RPC_BSC_TESTNET}"
test = "${RPC_TEST}"
